device:
  layer: rpi3

image:
  layer: image-rpios
  boot_part_size: 256M
  root_part_size: 2G
  name: netalertx-rpi
  compression: none

layer:
  base: bookworm-minbase
  custom: [docker-debian-bookworm, netalertx]
