device:
  layer: rpi3

image:
  layer: image-rpios
  boot_part_size: 256M
  root_part_size: 2G
  name: netalertx-rpi
  compression: none

layer:
  base: bookworm-minbase
  # Include RPI-specific packages for first-boot configuration
  extra:
    - rpi-debian-bookworm
  custom: netalertx
